version: 2.1

jobs:

  build:
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | bash - 
            apt install -y nodejs

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build app
          command: nmp run build

      - run:
          name: Build Docker image
          command: |
            docker build -f Dockerfile -t node-app .
            docker login -u semajkp4 -p JG!4727xd
            docker push node-app:latest

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy to DigitalOcean Kubernetes
          command: |
            echo "$KUBE_CONFIG" | base64 --decode > kubeconfig.yaml
            kubectl --kubeconfig kubeconfig.yaml apply -f deployment.yaml
            kubectl --kubeconfig kubeconfig.yaml apply -f service.yaml

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
